const services = [
    {
        id: 1,
        name: "Haematology",
        image: "https://i.ibb.co/6JpmD4y/haematology-1.png",
        price: 70,
        decs: "Haematology is the specialty responsible for the diagnosis and management of a wide range of benign and malignant disorders of the red and white blood cells, platelets and the coagulation system in adults and children.",
        description: "Haematology involves the diagnosis and treatment of patients who have disorders of the blood and bone marrow. Whilst a major part of a haematologist’s time is spent in providing direct clinical care to patients, diagnostic work in the laboratory is also a significant part of their work.Haematology is the specialty responsible for the diagnosis and management of a wide range of benign and malignant disorders of the red and white blood cells, platelets and the coagulation system in adults and children.Haematologists care directly for patients on hospital wards and out patient clinics. Their patients may have a serious life- threatening illness such as leukaemia, lymphoma or myeloma that requires chemotherapy. They also advise GPs about how to care for patients in their homes. Some haematologists specialise in diseases affecting the blood coagulation system such as haemophilia, while others  provide expertise in the areas of blood transfusion or disorders of haemoglobin such as sickle cell disease.Haematologists work very closely with other health professionals including GPs, pharmacists and specialist nurses, advising colleagues in hospital and primary care.For example, haematologists are the pathologists who receive blood samples from GP surgeries and check them for abnormalities. They look at blood film and, for example, if they suspect leukaemia, can assess the patient, explain concerns, perform a bone marrow biopsy and examine and interpret the samples. The diagnosis can be done within a few hours, since in some cases treatment must be started immediately."
    },
    {
        id: 2,
        name: "ECG",
        image: "https://i.ibb.co/tCxMW8j/ecg-2.png",
        price: 120,
        decs: "An electrocardiogram (ECG) is a simple test that can be used to check your heart's rhythm and electrical activity. Sensors attached to the skin are used to detect the electrical signals produced by your heart each time it beats.",
        description: "An electrocardiogram (ECG) is a simple test that can be used to check your heart's rhythm and electrical activity.Sensors attached to the skin are used to detect the electrical signals produced by your heart each time it beats.These signals are recorded by a machine and are looked at by a doctor to see if they're unusual.An ECG may be requested by a heart specialist (cardiologist) or any doctor who thinks you might have a problem with your heart, including your GP.The test can be carried out by a specially trained healthcare professional at a hospital, a clinic or at your GP surgery.Despite having a similar name, an ECG isn't the same as an echocardiogram, which is a scan of the heart."
    },
    {
        id: 3,
        name: "Vaccination",
        image: "https://i.ibb.co/9nhC4Fv/Vaccination-3.png",
        price: 90,
        decs: "Immunization is a global health and development success story, saving millions of lives every year. Vaccines reduce risks of getting a disease by working with your body’s natural defences to build protection. When you get a vaccine, your immune system responds.",
        description: "We now have vaccines to prevent more than 20 life-threatening diseases, helping people of all ages live longer, healthier lives. Immunization currently prevents 2-3 million deaths every year from diseases like diphtheria, tetanus, pertussis, influenza and measles.Immunization is a key component of primary health care and an indisputable human right. It’s also one of the best health investments money can buy. Vaccines are also critical to the prevention and control of infectious-disease outbreaks. They underpin global health security and will be a vital tool in the battle against antimicrobial resistance.Yet despite tremendous progress, far too many people around the world – including nearly 20 million infants each year – have insufficient access to vaccines. In some countries, progress has stalled or even reversed, and there is a real risk that complacency will undermine past achievements.Global vaccination coverage – the proportion of the world’s children who receive recommended vaccines – has remained the same over the past few years."
    },
    {
        id: 4,
        name: "Echocardiogram",
        image: "https://i.ibb.co/qJDH6T0/echocardiogram-4.png",
        price: 170,
        decs: "The heart is a two-stage electrical pump that circulates blood throughout the body. The anatomy includes four chambers and four valves. For the heart to function normally these structures need to be intact and the heart muscle needs to beat in a coordinated fashion, so that blood flows in and out of each chamber in the proper direction.",
        description: "An echocardiogram (echo=sound + card=heart + gram=drawing) is an ultrasound test that can evaluate the structures of the heart, as well as the direction of blood flow within it. Technicians specially trained in echocardiography produce the images and videos, often using a special probe or transducer that is placed in various places on the chest wall, to view the heart from different directions. Cardiologists, or heart specialists, are trained to evaluate these images to assess heart function and provide a report of the results.The echocardiogram is just one of the many tests that can be done to evaluate heart anatomy and function.An electrocardiogram(EKG, ECG) is the most common heart tracing done.Electrodes are placed on the chest wall and collect information about the electrical activity of the heart.Aside from the rate and rhythm of the heartbeat, the EKG can provide indirect evidence of blood flow within arteries to heart muscle and the thickness of heart muscle.Cardiac catheterization is an invasive test performed by a cardiologist, where a catheter is threaded into the coronary arteries(those arteries that supply the heart muscle with blood) through the femoral artery in the groin, the radial artery in the wrist, or the brachial artery in the elbow.Dye is injected into the coronary arteries looking for blockage.In some instances, the blockage can be corrected by balloon angioplasty where a balloon is inflated at the level of blockage, re- establishing blood flow.A stent can be used to keep the artery open.This test can also assess the size and function of the heart chambers and valves, and the major arteries and veins that enter and leave the heart."
    },
    {
        id: 5,
        name: "X-Ray",
        image: "https://i.ibb.co/YjBrhm5/x-ray-5.png",
        price: 140,
        decs: "An electromagnetic wave of high energy and very short wavelength, which is able to pass through many materials opaque to light.a photographic or digital image of the internal composition of something, especially a part of the body, produced by X-rays being passed through it and being absorbed to different degrees by different materials.",
        description: "Before their discovery in 1895, X-rays were just a type of unidentified radiation emanating from experimental discharge tubes. They were noticed by scientists investigating cathode rays produced by such tubes, which are energetic electron beams that were first observed in 1869. Many of the early Crookes tubes (invented around 1875) undoubtedly radiated X-rays, because early researchers noticed effects that were attributable to them, as detailed below. Crookes tubes created free electrons by ionization of the residual air in the tube by a high DC voltage of anywhere between a few kilovolts and 100 kV. This voltage accelerated the electrons coming from the cathode to a high enough velocity that they created X-rays when they struck the anode or the glass wall of the tube.The earliest experimenter thought to have (unknowingly) produced X-rays was actuary William Morgan. In 1785 he presented a paper to the Royal Society of London describing the effects of passing electrical currents through a partially evacuated glass tube, producing a glow created by X-rays.[5][6] This work was further explored by Humphry Davy and his assistant Michael Faraday."
    },
    {
        id: 6,
        name: "MRI",
        image: "https://i.ibb.co/JqfdKKj/mri-scan-6.png",
        price: 200,
        decs: "Magnetic resonance imaging (MRI) is a medical imaging technique that uses a magnetic field and computer-generated radio waves to create detailed images of the organs and tissues in your body.",
        description: "MRIs employ powerful magnets which produce a strong magnetic field that forces protons in the body to align with that field. When a radiofrequency current is then pulsed through the patient, the protons are stimulated, and spin out of equilibrium, straining against the pull of the magnetic field. When the radiofrequency field is turned off, the MRI sensors are able to detect the energy released as the protons realign with the magnetic field. The time it takes for the protons to realign with the magnetic field, as well as the amount of energy released, changes depending on the environment and the chemical nature of the molecules. Physicians are able to tell the difference between various types of tissues based on these magnetic properties.To obtain an MRI image, a patient is placed inside a large magnet and must remain very still during the imaging process in order not to blur the image. Contrast agents (often containing the element Gadolinium) may be given to a patient intravenously before or during the MRI to increase the speed at which protons realign with the magnetic field. The faster the protons realign, the brighter the image."
    }
]